### ISSUE TITLE
version 1.4.0 - ExtractorException may not inherit from final class ResolverException

### ISSUE THREAD

**Issue by koentibben** [jojo1981/data-resolver#1]
`Class Jojo1981\DataResolver\Extractor\Exception\ExtractorException may not inherit from final class (Jojo1981\DataResolver\Exception\ResolverException) in /data/vendor/jojo1981/data-resolver/src/Extractor/Exception/ExtractorException.php on line 17`

**Comment by jojo1981** [comment]
I will fix this.

**Comment by jojo1981** [comment]
Fixed in version 1.6.1
